import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perc asaru maju</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <p>section is here</p>
      </section>

      <footer className={styles.footer}>
        <p>Footer</p>
      </footer>
    </div>
  )
}
